# Generated by Django 2.2 on 2020-04-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_todolist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='todo_photos'),
        ),
    ]
