# Generated by Django 2.2 on 2020-04-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_todolist_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
