# Generated by Django 2.2 on 2020-04-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_todolist_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='count',
            field=models.IntegerField(default=10),
        ),
    ]
